### ISSUE TITLE
Sirens can fall down when shot at

### ISSUE THREAD

**Issue by KJeff01** [BLOODWOLF333/Brutal-Doom-Community-Expansion#217]
### Version
Development v0.4.2

### Environment
Computer

### Port
Zandronum 3.0.1

### Description
So, about the most useless bug report ever but I'll report it anyway. In seemingly uncommon and random instances, it's possible to shoot at the sirens on E1M1 and get them to fall down and not break. They also don't fall normal in that they slowly fall a little bit, stop, then fall some more before hovering at some final destination.

Amusingly, one can trap the player if they step on it since it'll zip back up to the ceiling and you can't escape from the ceiling in this case. The second screenshot shows an example of this happening.

![fall1](https://user-images.githubusercontent.com/22485442/95503042-662acc00-0970-11eb-9781-1a92e0262956.png)

![fall2](https://user-images.githubusercontent.com/22485442/95503058-6a56e980-0970-11eb-87a0-b371a332688a.png)

**Comment by BLOODWOLF333** [comment]
I thought I fixed this though I have never been able to reproduce it.  And this is on Zand and not GZDoom correct?  And no other mods are load that would overwrite the MapSpecificDec.txt file or the BDECAlarm actor?

**Comment by KJeff01** [comment]
Yep, Zandronum. And no other mods touch the actor or file you mentioned. I loaded it up using only the expansion mod and it still happened.

Some more notes:
1. Might be caused if a bullet hits the base of the siren. Hard to tell.
2. Siren dropping movement appears to be tied to player movement. They move down only if I move.

Happens on the latest 21.4.3 release too but I'm holding off an serious playthroughs since it appears to have some issues at the moment (flashlight doesn't work and the vehicle is missing on the E1M1 map despite the fire decoration still being there...).

**Comment by BLOODWOLF333** [comment]
> Happens on the latest 21.4.3 release too but I'm holding off on serious playthroughs with that version since it appears to have some issues at the moment (flashlight doesn't work and the vehicle is missing on the E1M1 map despite the fire decoration/effect still being there...).

Yeah I found that flashlight screw up after I uploaded 21.4.3 so, that one is already fixed.
![Screenshot_Doom_20201009_145041](https://user-images.githubusercontent.com/16950832/95625876-dc95ff80-0a3e-11eb-855f-d811f9b73ce1.png)
And the dropship is appearing for me in the repo's current state.  Maybe I already added back in a missing file that caused that in 21.4.3
