### ISSUE TITLE
The Rifle and the death states

### ISSUE THREAD

**Issue by DuyGamerLHB** [BLOODWOLF333/Brutal-Doom-Community-Expansion#407]
### Description:
- **The assault rifle** skips the empty mag check and shoots an extra non-existent round when you left click immediately right after you aim down the sights and scope, so this happens in the two states: **Fire2** and **Fire3**, I tried making them go to NoAmmo like the **Fire** state and it solved the problem.

- The death state of the zombiemen getting cut in half alive horizontally spawns both **DeadZombieman_Half** and **DeadZombiemanJustLegsAreLeft** causes him to spawn 2 pair of legs because those 2 actors use the same stats and sprite. It can be found in **Zombiemen.txt**

- Also remember the issue about the **dying sergeant/shotgun guy** who got his leg blown off? He now regrows his leg if he gets gibbed by a **Super Shotgun**, I think you should make him invisible and spawn a sarge leg, two arms, a sarge head along with some guts and bits

- The actor **BrutalizedCommandoBlasted** spawns an extra pair of legs when it gets shot, kicked or walked on/over after the animation has finished, this was caused by the line **TNT1 A -1**, can be solved by simply removing that line. And this can be found in **DyingGuys.txt**

- The corpse of the zombie scientist that had its **right body blown off** spawns another corpse with his whole upper body remain intact when it reaches the death state. One of the zombie scientist corpse actors also spawns a **one-leg dead zombieman** when it dies, possibly the one with its arm shot off. I also found this in **LabGuy.txt**

- (Edited) The Chaingun guy's dismembered arm sometimes renders as a normal arm when it gets kicked around, and it was the GibChainArm actor due to the missing Pain state

- (Edit 2) The stretched weapon sprites can be fixed by setting Weapon.ScaleX and Weapon.ScaleY to 1.2 in ClassicWeapons.txt and DefaultWeapons.txt

- (Edit 3 Bruh how did I forget about this one completely?) The **sergeant execution** actor uses the **zombieman head explode effect** instead of the sarge one

That's all I found and fixed when I was working on my own fork. The zombieman, scientist and sergeant dead bodies also have the missing **no head and no leg** variants but that requires extra sprites and script lines

**Comment by BLOODWOLF333** [comment]
Your using 21.13.2 or 21.13.1?  And you already reported and I fixed the firing immediately after ADS with the rifle https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/issues/402

**Comment by DuyGamerLHB** [comment]
The latest version, you forgot to make the two fire states check for no ammo

**Comment by DuyGamerLHB** [comment]
Ah shoot i forgot something else, the Chaingun guy's dismembered arm sometimes renders as a normal arm when it gets kicked around, and it was the GibChainArm actor

**Comment by BLOODWOLF333** [comment]
What stretched weapon sprites?

**Comment by BLOODWOLF333** [comment]
> (Edit 2) The stretched weapon sprites can be fixed by setting Weapon.ScaleX and Weapon.ScaleY to 1.2 in ClassicWeapons.txt and DefaultWeapons.txt

That's everything except this.  I have no idea what you're talking about with stretched weapons sprites.  You must be specific I cannot read your mind, I dont have the same setup as you, probably not using the same resolution, etc you must be specific and explain, don't give me vague reports.  I dont see anything wrong with the weapons on my side.

**Comment by BLOODWOLF333** [comment]
No there is nothing wrong with the weapon sprites.  The render engine is stretching the sprites which are all 5:4 aspect ratio images to 16:9 or 16:10 whatever AR your using, there is nothing wrong and Im not going to risk screwing this up for all the other resolutions out there that people are playing on.  No one else is bothered by or even noticed this so, nah that is way too OCD for me I'll pass.

**Comment by DuyGamerLHB** [comment]
Aight
